[package]
name = "nope-the-hoop-proto"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
ciborium = "0.2.1"
serde = { version = "1.0.192", features = ["derive"] }
